// exampleData = {
//   project: "clean the house",
//   tasks: [
//     {
//       title: "vacuum",
//       description: "",
//       priority:"",
//       deadLine: ,
//       isComplete: false,
//       completedAt: ,
//       createdAt: ,
//       assignedTo: "Angie",
//       completedBy: null,
//       hoursNeeded: 25,
//   }, 
//   {
//     title: "dust",
//     description: "",
//     priority:"",
//     deadLine: ,
//     isComplete: false,
//     completedAt: ,
//     createdAt: ,
//     assignedTo: "Angie",
//     completedBy: null,
//     timeNeededInHours: 25,
//   }, 
//   {
//     title: "cleanwindowsills",
//     description: "",
//     priority:"",
//     deadLine: ,
//     isComplete: false,
//     completedAt: ,
//     createdAt: ,
//     assignedTo: "Angie",
//     completedBy: null,
//     timeNeededInHours: 25,
//   }, 
//   {
//     title: "dishes",
//     description: "",
//     priority:"",
//     deadLine: ,
//     isComplete: false,
//     completedAt: ,
//     createdAt: ,
//     assignedTo: "Angie",
//     completedBy: null,
//     timeNeededInHours: 25,
//   },
// };

